const router=require('express').Router()
const moviesController = require('../controllers/movies.controller')
const verify=require('../verifyToken')
const upload = require('./middlewares/uploadFile')
router.get("/find/:id",moviesController.FindById)
var uploadMovie = upload.fields([{name:'img',maxCount:1},{name:'imgSm',maxCount:1},{name:'imgTitle',maxCount:1},{name:'trailer',maxCount:1},{name:'video',maxCount:1}])
router.post("/add",uploadMovie,moviesController.Add)
router.post("/multipleadd",uploadMovie,moviesController.MultipleAdd)
router.put("/update/:id",verify,moviesController.UpdateById)
router.put("/update",verify,moviesController.Update)
router.delete("/delete/:id",verify,moviesController.Delete)
router.post("/random",moviesController.GetRandomList)
router.get("/cat",moviesController.Gegenrelist)
router.get("/",moviesController.GetAllList)
module.exports=router