const statusCodes = 
[
  { code: 202, phrase: 'Accepted' },
  { code: 502, phrase: 'Bad Gateway' },
  { code: 400, phrase: 'Bad Request' },
  { code: 409, phrase: 'Conflict' },
  { code: 100, phrase: 'Continue' },
  { code: 201, phrase: 'Created' },
  { code: 417, phrase: 'Expectation Failed' },
  { code: 424, phrase: 'Failed Dependency' },
  { code: 403, phrase: 'Forbidden' },
  { code: 504, phrase: 'Gateway Timeout' },
  { code: 410, phrase: 'Gone' },
  { code: 505, phrase: 'HTTP Version Not Supported' },    
  { code: 418, phrase: "I'm a teapot" },
  { code: 419, phrase: 'Insufficient Space on Resource' },
  { code: 507, phrase: 'Insufficient Storage' },
  { code: 500, phrase: 'Internal Server Error' },
  { code: 411, phrase: 'Length Required' },
  { code: 423, phrase: 'Locked' },
  { code: 420, phrase: 'Method Failure' },
  { code: 405, phrase: 'Method Not Allowed' },
  { code: 301, phrase: 'Moved Permanently' },
  { code: 302, phrase: 'Moved Temporarily' },
  { code: 207, phrase: 'Multi-Status' },
  { code: 300, phrase: 'Multiple Choices' },
  { code: 511, phrase: 'Network Authentication Required' },
  { code: 204, phrase: 'No Content' },
  { code: 203, phrase: 'Non Authoritative Information' },
  { code: 406, phrase: 'Not Acceptable' },
  { code: 404, phrase: 'Not Found' },
  { code: 501, phrase: 'Not Implemented' },
  { code: 304, phrase: 'Not Modified' },
  { code: 200, phrase: 'OK' },
  { code: 206, phrase: 'Partial Content' },
  { code: 402, phrase: 'Payment Required' },
  { code: 308, phrase: 'Permanent Redirect' },
  { code: 412, phrase: 'Precondition Failed' },
  { code: 428, phrase: 'Precondition Required' },
  { code: 102, phrase: 'Processing' },
  { code: 407, phrase: 'Proxy Authentication Required' },
  { code: 431, phrase: 'Request Header Fields Too Large' },
  { code: 408, phrase: 'Request Timeout' },
  { code: 413, phrase: 'Request Entity Too Large' },
  { code: 414, phrase: 'Request-URI Too Long' },
  { code: 416, phrase: 'Requested Range Not Satisfiable' },
  { code: 205, phrase: 'Reset Content' },
  { code: 303, phrase: 'See Other' },
  { code: 503, phrase: 'Service Unavailable' },
  { code: 101, phrase: 'Switching Protocols' },
  { code: 307, phrase: 'Temporary Redirect' },
  { code: 429, phrase: 'Too Many Requests' },
  { code: 401, phrase: 'Unauthorized' },
  { code: 451, phrase: 'Unavailable For Legal Reasons' },
  { code: 422, phrase: 'Unprocessable Entity' },
  { code: 415, phrase: 'Unsupported Media Type' },
  { code: 305, phrase: 'Use Proxy' },
  { code: 421, phrase: 'Misdirected Request' }
]
module.exports = statusCodes
